### ISSUE TITLE
Possibility to highlight a square and return an array with all highlighted square positions 

### ISSUE THREAD

**Issue by gijs-ve** [Drumsin/aoe4-generated-map-debugger#3]
Will work on this :)

**Comment by Drumsin** [comment]
Hey @AdneCode 

I can see how this would be useful in a static map situation. Though I'm torn on this idea in a dynamic map situation - different sizes.

Give me an example workflow where you think this would be useful, while considering map scaling.

**Comment by gijs-ve** [comment]
It's only purpose is to make debugging easier, right? At the moment it is necessary to hover over every square in order to see it's positions. So if you have weird output and you want to fix this, you need to check your code to see why for example a certain terrain has an assigned terrain value. If there are multiple squares in a weird position, it is nice to highlight those on the Drumsin application in order to make life easier when editing the LUA (I am not sure how to name the app but everyone is referring to it as "Drumsin's app" so might as well stick to that).

**Comment by Drumsin** [comment]
Not specific enough with highlight output, and grid points don't translate dynamically with different map sizes.
